---
title: "Arm_Guy_150Project_Assign1_due_Apr19"
author: "Arm and Guy"
date: "April 19, 2021"
output: pdf_document
---

```{r global_options, include=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(message=FALSE, warning=FALSE, fig.height=3, fig.width=5, 
                      fig.align = "center")
library(tidyverse)
library(broom)
library(survival)
library(survminer)
library(readr)
```

```{r}
urlfile="https://raw.githubusercontent.com/gthampak/Arm_Guy_MATH150_Project/main/HELPdata.csv"

HELPdata <- read_csv(url(urlfile))
```

```{r}
HELPdata_survfit <- survfit(Surv(dayslink, linkstatus) ~ group, data=HELPdata)

ggsurvplot(HELPdata_survfit, conf.type = "TRUE") + 
  ggtitle("KM-curve")
```

```{r}
#histogram of age

ggplot(HELPdata, aes(x=age, fill = as.factor(smoker))) + 
  geom_histogram(binwidth = 1, color="black", fill="orange")
```

```{r}
ggplot(data=HELPdata) + 
  geom_bar(mapping=aes(x=age, fill=as.factor(smoker))) +
  ggtitle("Histogram of Patients' Age and Smoking")
```

```{r}
table(HELPdata$abuse)
```

